# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poster/rc/ui/postdata.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PostDataUi(object):
    def setupUi(self, PostDataUi):
        PostDataUi.setObjectName(_fromUtf8("PostDataUi"))
        PostDataUi.resize(744, 284)
        self.horizontalLayout = QtGui.QHBoxLayout(PostDataUi)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.postTypeLabel = QtGui.QLabel(PostDataUi)
        self.postTypeLabel.setObjectName(_fromUtf8("postTypeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.postTypeLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.postTypeText = QtGui.QRadioButton(PostDataUi)
        self.postTypeText.setObjectName(_fromUtf8("postTypeText"))
        self.postTypeButtonGroup = QtGui.QButtonGroup(PostDataUi)
        self.postTypeButtonGroup.setObjectName(_fromUtf8("postTypeButtonGroup"))
        self.postTypeButtonGroup.addButton(self.postTypeText)
        self.horizontalLayout_2.addWidget(self.postTypeText)
        self.postTypeLink = QtGui.QRadioButton(PostDataUi)
        self.postTypeLink.setChecked(True)
        self.postTypeLink.setObjectName(_fromUtf8("postTypeLink"))
        self.postTypeButtonGroup.addButton(self.postTypeLink)
        self.horizontalLayout_2.addWidget(self.postTypeLink)
        self.postTypeImage = QtGui.QRadioButton(PostDataUi)
        self.postTypeImage.setObjectName(_fromUtf8("postTypeImage"))
        self.postTypeButtonGroup.addButton(self.postTypeImage)
        self.horizontalLayout_2.addWidget(self.postTypeImage)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.postMessageLabel = QtGui.QLabel(PostDataUi)
        self.postMessageLabel.setObjectName(_fromUtf8("postMessageLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.postMessageLabel)
        self.postMessageText = QtGui.QTextEdit(PostDataUi)
        self.postMessageText.setTabChangesFocus(True)
        self.postMessageText.setObjectName(_fromUtf8("postMessageText"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.postMessageText)
        self.postNameLabel = QtGui.QLabel(PostDataUi)
        self.postNameLabel.setObjectName(_fromUtf8("postNameLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.postNameLabel)
        self.postNameText = QtGui.QLineEdit(PostDataUi)
        self.postNameText.setObjectName(_fromUtf8("postNameText"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.postNameText)
        self.postLinkLabel = QtGui.QLabel(PostDataUi)
        self.postLinkLabel.setObjectName(_fromUtf8("postLinkLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.postLinkLabel)
        self.postLinkText = QtGui.QLineEdit(PostDataUi)
        self.postLinkText.setObjectName(_fromUtf8("postLinkText"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.postLinkText)
        self.postPictureLabel = QtGui.QLabel(PostDataUi)
        self.postPictureLabel.setObjectName(_fromUtf8("postPictureLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.postPictureLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.postPictureText = QtGui.QLineEdit(PostDataUi)
        self.postPictureText.setObjectName(_fromUtf8("postPictureText"))
        self.horizontalLayout_3.addWidget(self.postPictureText)
        self.postPictureChooserButton = QtGui.QToolButton(PostDataUi)
        self.postPictureChooserButton.setEnabled(False)
        self.postPictureChooserButton.setObjectName(_fromUtf8("postPictureChooserButton"))
        self.horizontalLayout_3.addWidget(self.postPictureChooserButton)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(PostDataUi)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.postTargetsTabWidget = QtGui.QTabWidget(PostDataUi)
        self.postTargetsTabWidget.setDocumentMode(True)
        self.postTargetsTabWidget.setObjectName(_fromUtf8("postTargetsTabWidget"))
        self.tabGroups = QtGui.QWidget()
        self.tabGroups.setObjectName(_fromUtf8("tabGroups"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabGroups)
        self.verticalLayout.setContentsMargins(1, 1, 1, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupsListWidget = QtGui.QListWidget(self.tabGroups)
        self.groupsListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.groupsListWidget.setTabKeyNavigation(True)
        self.groupsListWidget.setAlternatingRowColors(True)
        self.groupsListWidget.setObjectName(_fromUtf8("groupsListWidget"))
        self.verticalLayout.addWidget(self.groupsListWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.totalGroupsLabel = QtGui.QLabel(self.tabGroups)
        self.totalGroupsLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.totalGroupsLabel.setObjectName(_fromUtf8("totalGroupsLabel"))
        self.horizontalLayout_4.addWidget(self.totalGroupsLabel)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.groupsFilterText = QtGui.QLineEdit(self.tabGroups)
        self.groupsFilterText.setObjectName(_fromUtf8("groupsFilterText"))
        self.horizontalLayout_4.addWidget(self.groupsFilterText)
        self.selectAllGroupsCheckBox = QtGui.QCheckBox(self.tabGroups)
        self.selectAllGroupsCheckBox.setObjectName(_fromUtf8("selectAllGroupsCheckBox"))
        self.horizontalLayout_4.addWidget(self.selectAllGroupsCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.postTargetsTabWidget.addTab(self.tabGroups, _fromUtf8(""))
        self.tabPages = QtGui.QWidget()
        self.tabPages.setObjectName(_fromUtf8("tabPages"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabPages)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pagesListWidget = QtGui.QListWidget(self.tabPages)
        self.pagesListWidget.setObjectName(_fromUtf8("pagesListWidget"))
        self.verticalLayout_2.addWidget(self.pagesListWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.totalPagesLabel = QtGui.QLabel(self.tabPages)
        self.totalPagesLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.totalPagesLabel.setObjectName(_fromUtf8("totalPagesLabel"))
        self.horizontalLayout_5.addWidget(self.totalPagesLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pagesFilterText = QtGui.QLineEdit(self.tabPages)
        self.pagesFilterText.setObjectName(_fromUtf8("pagesFilterText"))
        self.horizontalLayout_5.addWidget(self.pagesFilterText)
        self.selectAllPagesCheckBox = QtGui.QCheckBox(self.tabPages)
        self.selectAllPagesCheckBox.setObjectName(_fromUtf8("selectAllPagesCheckBox"))
        self.horizontalLayout_5.addWidget(self.selectAllPagesCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.postTargetsTabWidget.addTab(self.tabPages, _fromUtf8(""))
        self.tabLikes = QtGui.QWidget()
        self.tabLikes.setObjectName(_fromUtf8("tabLikes"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabLikes)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.likesListWidget = QtGui.QListWidget(self.tabLikes)
        self.likesListWidget.setObjectName(_fromUtf8("likesListWidget"))
        self.verticalLayout_3.addWidget(self.likesListWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.totalLikesLabel = QtGui.QLabel(self.tabLikes)
        self.totalLikesLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.totalLikesLabel.setObjectName(_fromUtf8("totalLikesLabel"))
        self.horizontalLayout_6.addWidget(self.totalLikesLabel)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.likesFilterText = QtGui.QLineEdit(self.tabLikes)
        self.likesFilterText.setObjectName(_fromUtf8("likesFilterText"))
        self.horizontalLayout_6.addWidget(self.likesFilterText)
        self.selectAllLikesCheckBox = QtGui.QCheckBox(self.tabLikes)
        self.selectAllLikesCheckBox.setObjectName(_fromUtf8("selectAllLikesCheckBox"))
        self.horizontalLayout_6.addWidget(self.selectAllLikesCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.postTargetsTabWidget.addTab(self.tabLikes, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.postTargetsTabWidget)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(2, 3)
        self.postMessageLabel.setBuddy(self.postMessageText)
        self.postNameLabel.setBuddy(self.postNameText)
        self.postLinkLabel.setBuddy(self.postLinkText)
        self.postPictureLabel.setBuddy(self.postPictureText)

        self.retranslateUi(PostDataUi)
        self.postTargetsTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.postTypeButtonGroup, QtCore.SIGNAL(_fromUtf8("buttonClicked(int)")), PostDataUi.postTypeChanged)
        QtCore.QObject.connect(self.postPictureChooserButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PostDataUi.choosePostPicture)
        QtCore.QObject.connect(self.groupsFilterText, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), PostDataUi.filterGroups)
        QtCore.QObject.connect(self.pagesFilterText, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), PostDataUi.filterPages)
        QtCore.QObject.connect(self.likesFilterText, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), PostDataUi.filterLikes)
        QtCore.QObject.connect(self.selectAllGroupsCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), PostDataUi.selectAllVisibleGroups)
        QtCore.QObject.connect(self.selectAllPagesCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), PostDataUi.selectAllVisiblePages)
        QtCore.QObject.connect(self.selectAllLikesCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), PostDataUi.selectAllVisibleLikes)
        QtCore.QMetaObject.connectSlotsByName(PostDataUi)

    def retranslateUi(self, PostDataUi):
        PostDataUi.setWindowTitle(_translate("PostDataUi", "Form", None))
        self.postTypeLabel.setText(_translate("PostDataUi", "Post Type", None))
        self.postTypeText.setText(_translate("PostDataUi", "Text", None))
        self.postTypeLink.setText(_translate("PostDataUi", "Link", None))
        self.postTypeImage.setText(_translate("PostDataUi", "Image", None))
        self.postMessageLabel.setText(_translate("PostDataUi", "Message", None))
        self.postNameLabel.setText(_translate("PostDataUi", "Name", None))
        self.postLinkLabel.setText(_translate("PostDataUi", "Link", None))
        self.postPictureLabel.setText(_translate("PostDataUi", "Picture", None))
        self.postPictureChooserButton.setText(_translate("PostDataUi", "...", None))
        self.totalGroupsLabel.setText(_translate("PostDataUi", "Total Groups : 0", None))
        self.selectAllGroupsCheckBox.setText(_translate("PostDataUi", "Select All", None))
        self.postTargetsTabWidget.setTabText(self.postTargetsTabWidget.indexOf(self.tabGroups), _translate("PostDataUi", "Groups", None))
        self.totalPagesLabel.setText(_translate("PostDataUi", "Total Pages : 0", None))
        self.selectAllPagesCheckBox.setText(_translate("PostDataUi", "Select All", None))
        self.postTargetsTabWidget.setTabText(self.postTargetsTabWidget.indexOf(self.tabPages), _translate("PostDataUi", "Pages", None))
        self.totalLikesLabel.setText(_translate("PostDataUi", "Total Likes : 0", None))
        self.selectAllLikesCheckBox.setText(_translate("PostDataUi", "Select All", None))
        self.postTargetsTabWidget.setTabText(self.postTargetsTabWidget.indexOf(self.tabLikes), _translate("PostDataUi", "Likes", None))

