# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poster/rc/ui/poster.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PosterUi(object):
    def setupUi(self, PosterUi):
        PosterUi.setObjectName(_fromUtf8("PosterUi"))
        PosterUi.resize(984, 503)
        PosterUi.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(PosterUi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.connectionStatusLabel = QtGui.QLabel(self.frame)
        self.connectionStatusLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.connectionStatusLabel.setFrameShape(QtGui.QFrame.Box)
        self.connectionStatusLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.connectionStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionStatusLabel.setObjectName(_fromUtf8("connectionStatusLabel"))
        self.gridLayout.addWidget(self.connectionStatusLabel, 2, 5, 1, 1)
        self.aboutButton = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon)
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.gridLayout.addWidget(self.aboutButton, 2, 2, 1, 1)
        self.userNameLabel = QtGui.QLabel(self.frame)
        self.userNameLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.userNameLabel.setFrameShape(QtGui.QFrame.Box)
        self.userNameLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.userNameLabel.setText(_fromUtf8(""))
        self.userNameLabel.setObjectName(_fromUtf8("userNameLabel"))
        self.gridLayout.addWidget(self.userNameLabel, 1, 4, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loginButton = QtGui.QPushButton(self.frame)
        self.loginButton.setMinimumSize(QtCore.QSize(80, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/login.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon1)
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.horizontalLayout_4.addWidget(self.loginButton)
        self.logoutButton = QtGui.QPushButton(self.frame)
        self.logoutButton.setMinimumSize(QtCore.QSize(80, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/logout.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon2)
        self.logoutButton.setObjectName(_fromUtf8("logoutButton"))
        self.horizontalLayout_4.addWidget(self.logoutButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 4, 1, 1)
        self.profilePictureLabel = QtGui.QLabel(self.frame)
        self.profilePictureLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.profilePictureLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.profilePictureLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.profilePictureLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.profilePictureLabel.setText(_fromUtf8(""))
        self.profilePictureLabel.setScaledContents(True)
        self.profilePictureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profilePictureLabel.setObjectName(_fromUtf8("profilePictureLabel"))
        self.gridLayout.addWidget(self.profilePictureLabel, 0, 6, 3, 1)
        self.userIdLabel = QtGui.QLabel(self.frame)
        self.userIdLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.userIdLabel.setFrameShape(QtGui.QFrame.Box)
        self.userIdLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.userIdLabel.setText(_fromUtf8(""))
        self.userIdLabel.setObjectName(_fromUtf8("userIdLabel"))
        self.gridLayout.addWidget(self.userIdLabel, 0, 4, 1, 2)
        self.appLogoLabel = QtGui.QLabel(self.frame)
        self.appLogoLabel.setMinimumSize(QtCore.QSize(80, 80))
        self.appLogoLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.appLogoLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.appLogoLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.appLogoLabel.setText(_fromUtf8(""))
        self.appLogoLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/img/icon.png")))
        self.appLogoLabel.setScaledContents(True)
        self.appLogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appLogoLabel.setObjectName(_fromUtf8("appLogoLabel"))
        self.gridLayout.addWidget(self.appLogoLabel, 0, 0, 3, 1)
        spacerItem = QtGui.QSpacerItem(353, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.settingsButton = QtGui.QPushButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon3)
        self.settingsButton.setObjectName(_fromUtf8("settingsButton"))
        self.gridLayout.addWidget(self.settingsButton, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.postTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.postTabWidget.setObjectName(_fromUtf8("postTabWidget"))
        self.verticalLayout_2.addWidget(self.postTabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.addPostButton = QtGui.QPushButton(self.centralwidget)
        self.addPostButton.setMinimumSize(QtCore.QSize(100, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPostButton.setIcon(icon4)
        self.addPostButton.setObjectName(_fromUtf8("addPostButton"))
        self.gridLayout_3.addWidget(self.addPostButton, 0, 0, 1, 1)
        self.loadPostButton = QtGui.QPushButton(self.centralwidget)
        self.loadPostButton.setMinimumSize(QtCore.QSize(100, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadPostButton.setIcon(icon5)
        self.loadPostButton.setObjectName(_fromUtf8("loadPostButton"))
        self.gridLayout_3.addWidget(self.loadPostButton, 2, 1, 1, 1)
        self.savePostButton = QtGui.QPushButton(self.centralwidget)
        self.savePostButton.setMinimumSize(QtCore.QSize(100, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePostButton.setIcon(icon6)
        self.savePostButton.setObjectName(_fromUtf8("savePostButton"))
        self.gridLayout_3.addWidget(self.savePostButton, 2, 0, 1, 1)
        self.removePostButton = QtGui.QPushButton(self.centralwidget)
        self.removePostButton.setMinimumSize(QtCore.QSize(100, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removePostButton.setIcon(icon7)
        self.removePostButton.setObjectName(_fromUtf8("removePostButton"))
        self.gridLayout_3.addWidget(self.removePostButton, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.minDelayLabel = QtGui.QLabel(self.centralwidget)
        self.minDelayLabel.setObjectName(_fromUtf8("minDelayLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.minDelayLabel)
        self.minDelaySpinBox = QtGui.QSpinBox(self.centralwidget)
        self.minDelaySpinBox.setMaximum(999999999)
        self.minDelaySpinBox.setProperty("value", 180)
        self.minDelaySpinBox.setObjectName(_fromUtf8("minDelaySpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.minDelaySpinBox)
        self.maxDelayLabel = QtGui.QLabel(self.centralwidget)
        self.maxDelayLabel.setObjectName(_fromUtf8("maxDelayLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.maxDelayLabel)
        self.maxDelaySpinBox = QtGui.QSpinBox(self.centralwidget)
        self.maxDelaySpinBox.setMaximum(999999999)
        self.maxDelaySpinBox.setProperty("value", 300)
        self.maxDelaySpinBox.setObjectName(_fromUtf8("maxDelaySpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.maxDelaySpinBox)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtGui.QFormLayout.SpanningRole, spacerItem1)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.sleepTimeLabel = QtGui.QLabel(self.centralwidget)
        self.sleepTimeLabel.setObjectName(_fromUtf8("sleepTimeLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.sleepTimeLabel)
        self.sleepTimeSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.sleepTimeSpinBox.setMaximum(999999999)
        self.sleepTimeSpinBox.setProperty("value", 1200)
        self.sleepTimeSpinBox.setObjectName(_fromUtf8("sleepTimeSpinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sleepTimeSpinBox)
        self.sleepAfterLabel = QtGui.QLabel(self.centralwidget)
        self.sleepAfterLabel.setObjectName(_fromUtf8("sleepAfterLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.sleepAfterLabel)
        self.sleepAfterSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.sleepAfterSpinBox.setMinimum(1)
        self.sleepAfterSpinBox.setMaximum(999999999)
        self.sleepAfterSpinBox.setProperty("value", 30)
        self.sleepAfterSpinBox.setObjectName(_fromUtf8("sleepAfterSpinBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.sleepAfterSpinBox)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtGui.QFormLayout.SpanningRole, spacerItem2)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.posterTimerLabel = QtGui.QLabel(self.centralwidget)
        self.posterTimerLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.posterTimerLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.posterTimerLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.posterTimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.posterTimerLabel.setObjectName(_fromUtf8("posterTimerLabel"))
        self.verticalLayout_4.addWidget(self.posterTimerLabel)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.posterProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.posterProgressBar.setProperty("value", 0)
        self.posterProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.posterProgressBar.setObjectName(_fromUtf8("posterProgressBar"))
        self.verticalLayout_4.addWidget(self.posterProgressBar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.postToWallCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.postToWallCheckBox.setChecked(True)
        self.postToWallCheckBox.setObjectName(_fromUtf8("postToWallCheckBox"))
        self.gridLayout_2.addWidget(self.postToWallCheckBox, 0, 0, 1, 1)
        self.postLikeHumanCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.postLikeHumanCheckBox.setEnabled(False)
        self.postLikeHumanCheckBox.setObjectName(_fromUtf8("postLikeHumanCheckBox"))
        self.gridLayout_2.addWidget(self.postLikeHumanCheckBox, 0, 1, 1, 1)
        self.stopOnErrorsCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.stopOnErrorsCheckBox.setChecked(True)
        self.stopOnErrorsCheckBox.setObjectName(_fromUtf8("stopOnErrorsCheckBox"))
        self.gridLayout_2.addWidget(self.stopOnErrorsCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.posterStartButton = QtGui.QPushButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.posterStartButton.setIcon(icon8)
        self.posterStartButton.setObjectName(_fromUtf8("posterStartButton"))
        self.horizontalLayout.addWidget(self.posterStartButton)
        self.posterPauseButton = QtGui.QPushButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.posterPauseButton.setIcon(icon9)
        self.posterPauseButton.setObjectName(_fromUtf8("posterPauseButton"))
        self.horizontalLayout.addWidget(self.posterPauseButton)
        self.posterResumeButton = QtGui.QPushButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/resume.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.posterResumeButton.setIcon(icon10)
        self.posterResumeButton.setObjectName(_fromUtf8("posterResumeButton"))
        self.horizontalLayout.addWidget(self.posterResumeButton)
        self.posterCancelButton = QtGui.QPushButton(self.centralwidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.posterCancelButton.setIcon(icon11)
        self.posterCancelButton.setObjectName(_fromUtf8("posterCancelButton"))
        self.horizontalLayout.addWidget(self.posterCancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.appLogText = QtGui.QTextEdit(self.centralwidget)
        self.appLogText.setReadOnly(True)
        self.appLogText.setObjectName(_fromUtf8("appLogText"))
        self.verticalLayout_2.addWidget(self.appLogText)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(3, 1)
        self.frame.raise_()
        self.appLogText.raise_()
        self.postTabWidget.raise_()
        PosterUi.setCentralWidget(self.centralwidget)
        self.minDelayLabel.setBuddy(self.minDelaySpinBox)
        self.maxDelayLabel.setBuddy(self.maxDelaySpinBox)
        self.sleepTimeLabel.setBuddy(self.sleepTimeSpinBox)
        self.sleepAfterLabel.setBuddy(self.sleepAfterSpinBox)

        self.retranslateUi(PosterUi)
        self.postTabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.loginButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.login)
        QtCore.QObject.connect(self.logoutButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.logout)
        QtCore.QObject.connect(self.posterStartButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.startPosterTask)
        QtCore.QObject.connect(self.posterPauseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.pausePosterTask)
        QtCore.QObject.connect(self.posterResumeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.resumePosterTask)
        QtCore.QObject.connect(self.posterCancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.stopPosterTask)
        QtCore.QObject.connect(self.aboutButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.about)
        QtCore.QObject.connect(self.addPostButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.addPostTab)
        QtCore.QObject.connect(self.removePostButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.removePostTab)
        QtCore.QObject.connect(self.savePostButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.savePostToFile)
        QtCore.QObject.connect(self.loadPostButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.loadPostFromFile)
        QtCore.QObject.connect(self.settingsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PosterUi.settings)
        QtCore.QMetaObject.connectSlotsByName(PosterUi)
        PosterUi.setTabOrder(self.loginButton, self.logoutButton)
        PosterUi.setTabOrder(self.logoutButton, self.settingsButton)
        PosterUi.setTabOrder(self.settingsButton, self.aboutButton)
        PosterUi.setTabOrder(self.aboutButton, self.postTabWidget)
        PosterUi.setTabOrder(self.postTabWidget, self.addPostButton)
        PosterUi.setTabOrder(self.addPostButton, self.removePostButton)
        PosterUi.setTabOrder(self.removePostButton, self.savePostButton)
        PosterUi.setTabOrder(self.savePostButton, self.loadPostButton)
        PosterUi.setTabOrder(self.loadPostButton, self.minDelaySpinBox)
        PosterUi.setTabOrder(self.minDelaySpinBox, self.maxDelaySpinBox)
        PosterUi.setTabOrder(self.maxDelaySpinBox, self.sleepTimeSpinBox)
        PosterUi.setTabOrder(self.sleepTimeSpinBox, self.sleepAfterSpinBox)
        PosterUi.setTabOrder(self.sleepAfterSpinBox, self.postToWallCheckBox)
        PosterUi.setTabOrder(self.postToWallCheckBox, self.postLikeHumanCheckBox)
        PosterUi.setTabOrder(self.postLikeHumanCheckBox, self.stopOnErrorsCheckBox)
        PosterUi.setTabOrder(self.stopOnErrorsCheckBox, self.posterStartButton)
        PosterUi.setTabOrder(self.posterStartButton, self.posterPauseButton)
        PosterUi.setTabOrder(self.posterPauseButton, self.posterResumeButton)
        PosterUi.setTabOrder(self.posterResumeButton, self.posterCancelButton)
        PosterUi.setTabOrder(self.posterCancelButton, self.appLogText)

    def retranslateUi(self, PosterUi):
        PosterUi.setWindowTitle(_translate("PosterUi", "MainWindow", None))
        self.connectionStatusLabel.setText(_translate("PosterUi", "<html><head/><body><p><span style=\" color:#ff0000;\">Disconnected</span></p></body></html>", None))
        self.aboutButton.setText(_translate("PosterUi", "About", None))
        self.loginButton.setText(_translate("PosterUi", "Login", None))
        self.logoutButton.setText(_translate("PosterUi", "Logout", None))
        self.settingsButton.setText(_translate("PosterUi", "settings", None))
        self.addPostButton.setText(_translate("PosterUi", "Add Post", None))
        self.loadPostButton.setText(_translate("PosterUi", "Load Post", None))
        self.savePostButton.setText(_translate("PosterUi", "Save Post", None))
        self.removePostButton.setText(_translate("PosterUi", "Remove Post", None))
        self.minDelayLabel.setText(_translate("PosterUi", "Min Delay", None))
        self.minDelaySpinBox.setSuffix(_translate("PosterUi", " s", None))
        self.maxDelayLabel.setText(_translate("PosterUi", "Max Delay", None))
        self.maxDelaySpinBox.setSuffix(_translate("PosterUi", " s", None))
        self.sleepTimeLabel.setText(_translate("PosterUi", "Sleep", None))
        self.sleepTimeSpinBox.setSuffix(_translate("PosterUi", " s", None))
        self.sleepAfterLabel.setText(_translate("PosterUi", "After", None))
        self.sleepAfterSpinBox.setSuffix(_translate("PosterUi", " posts", None))
        self.posterTimerLabel.setText(_translate("PosterUi", "00:00:00:000", None))
        self.postToWallCheckBox.setText(_translate("PosterUi", "Post to my Wall", None))
        self.postLikeHumanCheckBox.setText(_translate("PosterUi", "Post like Human", None))
        self.stopOnErrorsCheckBox.setText(_translate("PosterUi", "Stop on Errors", None))
        self.posterStartButton.setText(_translate("PosterUi", "Start", None))
        self.posterPauseButton.setText(_translate("PosterUi", "Pause", None))
        self.posterResumeButton.setText(_translate("PosterUi", "Resume", None))
        self.posterCancelButton.setText(_translate("PosterUi", "Cancel", None))

import resources_rc
